name: Download Dota2 Game Files

on:
  schedule:
    # Runs at 17:45 UTC (19:45 CEST, daylight saving time)
    - cron: "45 17 * * *"
    # Runs at 18:45 UTC (19:45 CET, standard time)
    - cron: "45 18 * * *"
  workflow_dispatch:

jobs:
  download:
    runs-on: ubuntu-latest

    permissions:
<<<<<<< HEAD
      contents: write # Allows GITHUB_TOKEN to commit and push changes.
=======
      contents: write 
>>>>>>> d9f8ccd8d1a442b6e56898af1d8e7c18d9720d8c

    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v3
        with:
<<<<<<< HEAD
          node-version: "20" # Specify Node.js version 20.
=======
          node-version: '20' 
>>>>>>> d9f8ccd8d1a442b6e56898af1d8e7c18d9720d8c
      - name: Download new game files
        run: npm install && node index.js '${{ secrets.USERNAME }}' '${{ secrets.PASSWORD }}'
      - name: Read manifestId.txt
        id: manifestId
        uses: juliangruber/read-file-action@v1
        with:
          path: ./static/manifestId.txt
      - name: Commit & push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "manifest ${{ steps.manifestId.outputs.content }}"
